### ISSUE TITLE
Estudar sobre o projeto SpaceInvaders

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#105]
- Estudar sobre o projeto SpaceInvaders (https://space.fabsoftware.itp.ifsp.edu.br/)

- Tentar responder as perguntas: o que é? para que serve? como usar? Quais tecnologias utilizam? Ideia de melhorias? Problemas?
- Fazer uma apresentação sobre o que aprendeu para apresentar aos demais membros do grupo na próxima semana.

**Comment by JoniEmann** [comment]
**O que é :** Space Invader é um jogo jogado somente no celular, cujo o intuito é derrotar as naves inimigas e conseguir o maior ponto possível para ascender no ranking. Utiliza as tecnologias de JavaScript e JASON para o ranking; seu modo de jogo é movimentando a tela de celular e o toque para soltar os raios para derrotar as naves inimigas.

**Para que serve :** Esse jogo serviu para apresentar e atrair o público para conhecer a fábrica durante o evento do IF-CASA ABERTA 2023, sendo um jogo com o predicado de chamar a atenção do pessoal para vir jogar e enfim conhecer sobre o projeto da fábrica.

**Como usar :** O jogo Space Invader tem uma forma bem específica de se jogar, primeiro, você vira a tela do seu celular de modo a deixa-la na horizontal e o jogo já inicia sozinho, contudo, você primeiro coloca seu nome para então jogar; Após isso, é necessário tocar na tela para a nave principal ( o jogador ) atirar e acertar a nave adversária, destruindo-a e conseguindo pontos para se classificar no ranking;

**Quais tecnologias utilizam :** JavaScript ( Funcionamento ) | JASON ( ranking ) | HTML ( Interface ) | CSS ( cenário )

**Ideia de melhorias :** Adição dum menu, adição de crossplay ( possibilidade de jogar num PC ), multiplayer ( dois jogadores ) e de design ( variação de inimigos que formam uma imagem, como, inimigos de cor branca, verde e vermelho que compõem a logo do IF ) e também a melhoria nos sons e barulhos e a movimentação da nave, adicionar fases.

**Problemas :** A Nave estar travando no canto da tela, os sons são altos e irritantes, o movimento é muito lento, dificuldade baixa;

**Comment by maLu70** [comment]
Space Invaders 

- Problemas: 
Se você destruir invasores o suficiente para passar por entre eles e esperar eles sumirem da tela, o jogo não acaba. Você continua subindo para sempre, sem adquirir pontuação e sem aparecer novos invasores ou encerrar o jogo.

- Melhorias: 
Trocar a posição da caixa para inserção do nome com a informação de virar a tela, para que seja mais intuitivo adicionar o nome antes de começar o jogo.
Adicionar a informação de que deve ser inserido um nome.

- Outras ideias: 
Não limitar o número de invasores; deixar surgindo até que o jogador perca, aumentando a dificuldade de sobrevivência conforme maior pontuação.
