### ISSUE TITLE
Relatório mês de Junho

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#108]
Fazer o relatório do mês seguindo o padrão abaixo. 
Colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X + Y horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Leo2828** [comment]
# Junho
## Semana 22

- 5 horas: Estilização das páginas de projetos e membros, ajustes nos arquivos markdown dos projetos e mudanças nos layouts
- 5 horas: Ajuste gerais e implementação de responsividade na pagina inicial
- 5 horas: Finalização de estilização e responsividade do site
- 5 horas: Reunião semanal com mostra da versão final do site e coleta de feedbacks

## Semana 23

- 5 horas: Ajustes gerais e adição da nova logo e suas variações
- 5 horas: Modificações de partes do site
- 5 horas: Estudo sobre SEO para adição do site da fábrica e criação da página de erro 404
- 5 horas: Mostra da versão final do site com publicação do site: https://dev.fabsoftware.itp.ifsp.edu.br/ para testes

## Semana 24

- 5 horas: Criação de layout para página do geek if
- 5 horas: Criação da página: "seja um patrocinador" para o site do geek if
- 5 horas: Alteração dos depoimentos por videos com legenda, e auxilio aos voluntários
- 5 horas: Reunião com o encerramento das modificações do site da fábrica e substituição do site no ar

## Semana 25

- 5 horas: Pesquisa sobre o projeto pong de acordo com a issue (link da issue) e criação das páginas em breve e retrospectiva do geek if
- 5 horas: Criação da página cronograma do site geek if e continuição do estudo do projeto pong
- 5 horas: Atividade de integração.
- 5 horas: Atividade de integração.

## Total: 80 horas

**Comment by maLu70** [comment]
Relatório de Junho

Semana 22:
-  2 Horas: Padronização do formato dos vídeos dos depoimentos
- 5 Horas: Adicionado legenda nos vídeos dos antigos membros da fábrica
- 1 Hora: Pesquisa de formas de melhoria para a qualidade dos vídeos 
- 3 Horas: Mudança da resolução e formato das imagens para o IFAQ
- 3 Horas: Finalização dos últimos áudios necessários para o IFAQ

Semana 23:

- 1 Hora: Criação de uma playlist com os vídeos dos depoimentos no YouTube da Fábrica
- 3 Horas: Ajustes finais no IFAQ; fotos da frente, modificações dos áudios com problemas e adição da capa final e inicial

Semana 24: 
- 2 Horas: Estudo sobre o projeto space Invaders


Total: 20 Horas

**Comment by MarcosFabSoftware** [comment]
# Junho
## Semana 22
- 03 horas: Ocorreu a finalização dos áudios dos personagens

## Semana 23
- 05 horas: Foi adicionado uma capa inicial, corrigido a responsividade: imagem, texto e animação.
- 01 horas: Foi estilizado o código, para ficar mais fácil a leitura

## Semana 24
- 02 horas: Aconteceu a atualização da capa final para uma versão 2.0 e o conserto de bugs
- 02 horas: Ocorreu a adição de metade dos áudios das perguntas do Pica Pau e realizado testes

## Semana 25
- 02 horas: Realizou-se a finalização dos áudios do Pica Pau
- 02 horas: Foi adicionado metade dos áudios dos restantes dos personagens, nos seus respectivos documentos HTML
- 02 horas: Aconteceu a finalização da adição dos áudios de todos os personagens
- 05 horas: Foi arrumado o delay de todos os áudios dos personagens, para condizir com a animação do WebStories, concatenado a pagina inicial e o WebStories
- 02 horas: Ocorreu a adição de todas as imagens no documento HTML do Faustão




## Total: 26 horas

**Comment by JoniEmann** [comment]
### **Junho**

### **Semana 22**
3 horas: Organizando as questões da 1 até 10 em código no formato WebStories.
2 horas: Testando as perguntas e vendo se a padronização estava correta.
4 horas: Organização dos textos de cada pergunta, arrumando a responsividade de cada questão.
2 horas: Novamente testando as perguntas nos diversos dispositivos em relação a responsividade;

### **Semana 23**
4 horas: Baixando e pegando as imagens do drive do IFAQ e organizando-as em pastas respectivas as questões
2 horas: Com a padronização pronta, foi feita a alteração das imagens em cada questão com as imagens que estavam disponíveis no drive;
5 horas: Visto problemas na responsividade, foi realizada uma correção no tamanho e no enquadro das imagens em cada questão;
2 horas: Observando cada imagem, de cada questão, de cada dispositivo para ver se a responsividade estava correta.
1 hora: correção do bug observado um problema na transição da pergunta para a resposta, para dispositivos grandes o efeito zoom-in acusava aparecer antes do esperado.

### **Semana 24**
3 horas: Mesclagem dos áudios e das imagens;
1 hora: trabalhando em cima dos áudios agora, Marcos Kauan explicou como mexer com delay dos aúdios para sincronizar as imagens e os áudios.
3 horas: Trabalhando no delay do áudio, para sincronizar em relação as perguntas e respostas, fazendo o Stories não cortar mais ou o aúdio repetir.
2 horas: Sincronizando as imagens novamente em cada modelo html ( Otto, Pato Donald, Faustão e Pica-Pau )
2 horas: Colocando as capas e as imagens finais de cada Stories de cada voz.

### **Semana 25**
5 horas: Atividade de Integração.
5 horas: Atividade de Integração.

### **Total: 46 horas**
