### ISSUE TITLE
Relatório mês de Julho

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#109]
Fazer o relatório do mês seguindo o padrão abaixo. 
Colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X + Y horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Leo2828** [comment]
# Julho
## Semana 26

- 5 horas: Estudo do projeto pong.
- 5 horas: Continuação do estudo do projeto pong respondendo as perguntas de acordo com a issue: https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/issues/104#issue-2365158105 .
- 5 horas: Estudo da framework socket.io de acordo com a documentação presente no site: https://socket.io/.
- 5 horas: Reunião com apresentação sobre o projeto pong.

## Semana 27

- 5 horas: Tentativa de correção e melhorias no pong.
- 5 horas: Reunião relatando as dificuldades e oque foi aprendido com a ferramenta socket.io.

## Semana 28

- 5 horas: Tentativa de correção do projeto pong de acordo com a issue: https://github.com/fabsoftwareitp/pong.fabsoftware.itp.ifsp.edu.br/issues/2#issue-2391292568.
- 5 horas: Mudança da tela de controle para a tela do cliente, assim sincronizando as duas telas.
- 5 horas: Adição de algumas melhorias como por exemplo a tela de loading.
- 5 horas: Reunião com testes da sincronização do pong e idéias e soluções.

## Semana 29

- 5 horas: Estudo de um projeto semelhante ao pong para tentar solucionar os problemas do pong.
- 5 horas: Tentativa de empregar o metódo do projeto semelhante.
- 5 horas: Continuação da tentativa de adaptação.
- 5 horas: Reunião com resultados e requesitos de um novo projeto

## Semana 30

- 5 horas: Estudo de CMS para sugestão de ferramentas para novo projeto.
- 5 horas: Continuação do estudo e desenvolvimento de slides para apresentação.

## Total: 80 horas

**Comment by MarcosFabSoftware** [comment]
# Julho
## Semana 27
- 05 horas: Estudo do projeto pong, respondendo as perguntas
- 02 horas: Mudança no tamanho das imagens do IFAQ, tela inicial do WebStories
- 05 horas: Mudança no README do IFAQ, estelizando 
- 02 horas: Adicionado SEO, arrumado README do IFAQ
- 01 horas: Arrumado bugs

## Semana 28
- 02 horas: Tentativa de achar a branch main do Space Invaders, não sabia qual branch era a principal e não trabalhei no Space por isso. Nessa semana

## Semana 29
- 02 horas: Mudança no ranking para ficar mais bonito

## Semana 30
- 03 horas: Adicionado rodapé, desenvolvido por fábrica de software, adicionado botão jogar. Invés de virar a tela

## Semana 31
- 02 horas: Adicionado menu de opções, parte 1
- 04 horas: Menu de opções, parte 2
- 04 horas: Menu de opções, parte 3
- 04 horas: Menu de opções, parte 4

## Total: 36 horas

**Comment by maLu70** [comment]
### Julho

Semana 27

- 02 Horas: Estudo sobre o Space Invaders

Semana 28

- 02 Horas: Criação de Invasores com as cores do IF (Vermelho, verde, branco e laranja) para o SpaceInvaders.

Semana 29

- 02 Horas: Ajustes da tela inicial do Space Invaders; troca de posição da caixa de inserir o nome com a informação de virar o celular, adicionado a informação de adicionar um nome e troca da logo da fábrica.

Semana 30

- 05 Horas: Pesquisa de ideias de Landing Page para o site do Laboratório de PHI

Total: 11 Horas

**Comment by JoniEmann** [comment]
**Semana 27**

03 horas: Estudo do projeto Space Invaders. 

03 horas: Teste de bugs e de gambiarras possíveis no projeto Space Invaders. 

02 horas: Repassando o resultado dos estudos realizados em cima do space Invaders.

02 horas: Análise do código. 

**Semana 28**

02 horas: Estudo do ranking e suas funcionalidades, como foi aplicado. 

01 hora: Tentativa de mexer no array dos inimigos e seu pontos, mas, não havia o arquivo necessário para executar.

**Semana 29**

XXX. 

**Semana 30**

XXX. 

**Semana 31**

04 horas: Produção da ideia de camisa da Fabrica de Software;

**Total:** 17 horas
