### ISSUE TITLE
Comparativo de CMS

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#110]
Realizar uma pesquisa abrangente sobre diferentes Sistemas de Gerenciamento de Conteúdo (CMS) e apresentar uma análise comparativa dos seus recursos, vantagens e desvantagens. O objetivo é auxiliar na escolha do CMS mais adequado para as necessidades do novo projeto.

**Objetivo:**

* Identificar pelo menos 3 CMS populares e relevantes;
* Pesquisar e documentar as funcionalidades, recursos, vantagens e desvantagens de cada CMS selecionado.
* Criar uma apresentação clara e concisa que compare os CMS, destacando os pontos fortes e fracos de cada um.
* Fornecer recomendações baseadas na análise, justificando a escolha do CMS mais adequado para o projeto.

**Critérios de comparação:**

* Facilidade de uso
* Flexibilidade e personalização
* Suporte e comunidade
* Custo

**Entregáveis:**

* Documento com a pesquisa e análise dos CMS selecionados.
* Apresentação em slides comparando os CMS.
* Recomendação do CMS mais adequado, com justificativa.

**Comment by Leo2828** [comment]
PDF:
[CMS.pdf](https://github.com/user-attachments/files/16460788/CMS.pdf)

Link:
https://www.canva.com/design/DAGB2w7xfRg/b9sXzs-7RDpNO0uyOT-o8w/edit?utm_content=DAGB2w7xfRg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
