### ISSUE TITLE
Pesquisa de Templates de Landing Page para PHI Lab

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#111]
Realizar uma pesquisa de templates de landing page inspiradores para o desenvolvimento da página do Laboratório de Pneumática e Hidráulica (PHI Lab) do IFSP. A landing page deve apresentar as características e recursos do laboratório de forma clara, atrativa e profissional.

**Objetivo:**

* Identificar pelo menos 10 templates de landing page que se alinhem com o perfil do PHI Lab, considerando as seções e informações a serem apresentadas.
* Priorizar templates com design moderno, responsivo e que possibilitem a integração de imagens e vídeos de alta qualidade.
* Criar uma apresentação com os templates selecionados, destacando seus elementos chave e inspirações, considerando a paleta de cores do IFSP (ou sugestões de outras paletas).

**Cores:**
* Paleta de cores do IFSP como referência, aberta a sugestões de outras paletas que transmitam profissionalismo, tecnologia e inovação.

**Seções da Landing Page:**

* **Sobre o laboratório:**
    * Breve descrição da missão e objetivos do PHI Lab.
    * Slider com fotos gerais do laboratório.
* **Professores:**
    * Fotos, contatos e links para Lattes dos professores.
* **Equipamentos:**
    * Fotos e descrições dos equipamentos disponíveis no laboratório (referência: https://www.itapeva.unesp.br/#!/pesquisa/laboratorios-de-pesquisa/multiusuario/equipamentos/).
* **Disciplinas que usam o laboratório:**
    * Lista das disciplinas que utilizam o PHI Lab.
    * Links para os materiais das disciplinas e para as ementas.
* **Experimentos:**
    * Descrição dos tipos de experimentos realizados no laboratório:
        * Pneumática e Hidráulica
        * EletroPneumática e Eletrohidraulica
        * Sistemas Hidráulicos e Pneumáticos
        * Mecânica dos Fluídos
        * Máquinas de fluxo

**Entregáveis:**

* Documento com a lista de templates selecionados, links e breve descrição de cada um.
* Apresentação visual com os templates, destacando seus elementos chave e inspirações, considerando a paleta de cores.

**Comment by rafalmeida-ifsp** [comment]
Sugestões de sites para inspiração:

- https://www.utfpr.edu.br/
- https://www2.unesp.br/
- https://web.mit.edu/
- https://tec.mx/en#education

**Comment by maLu70** [comment]
[ideias.pdf](https://github.com/user-attachments/files/16551683/ideias.pdf)

**Comment by danilocbueno** [comment]
Pessoal, tem bastante coisa que vocês levantaram nas ideias e acabaram não utilizando nos protótipos, fiquem a vontade pra utilizar.
