### ISSUE TITLE
Protótipo Landing Page Laboratório

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#113]
Com base nos levantamentos da issue anterior [#111](https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/issues/111), criar um protótipo no Figma para a landing page do laboratório.

**Seções da Landing Page:**

* **Sobre o Laboratório:** Breve descrição da missão, visão e valores do laboratório.
* **Professores:** Apresentação dos professores, com fotos, áreas de expertise e links para perfis (se aplicável).
* **Equipamentos:** Lista dos principais equipamentos disponíveis no laboratório, com fotos e descrições concisas.
* **Disciplinas:** Cursos e disciplinas ministrados no laboratório, com links para mais informações (se aplicável).
* **Experimentos:** Destaque para os principais experimentos realizados no laboratório, com fotos e descrições curtas.

**Layout:**

Utilizar os assets disponíveis em: https://drive.google.com/drive/folders/1CBqT6_69c3oS4fPzmV6J-3tB3F7SfBfE?usp=sharing

@maLu70 : Seguir o exemplo de layout apresentado na reunião mais parecido com o layout de equipamentos.
@Leo2828: Seguir o exemplo com menu lateral.

**Entregáveis:**

* Link para o protótipo no Figma.

**Próximos Passos:**

* Revisão e feedback sobre o protótipo.
* Desenvolvimento da versão final da landing page.

**Comment by danilocbueno** [comment]
## Finalização
@maLu70 
- retirar o textos aleatórios
- adicionar um rodapé
- colocar o pattern (quadrado/formas geométricas) no destaque azul (https://www.svgbackgrounds.com/)
- adicionar o link do figma aqui na issue

@Leo2828 
- utilizar a paleta de cores do IF
- adicionar os textos referentes ao projeto que está no DOC
- fazer as seções 
- adicionar o link do figma aqui na issue

Usar as ideias que levantaram em: [ideias.pdf](https://github.com/user-attachments/files/16551683/ideias.pdf)

**Comment by Leo2828** [comment]
https://www.figma.com/design/vuOJjxGqS81j8ZgiaYEVdK/layout-philab?node-id=0-1&t=OTAWWfRFEjXP85xW-0

**Comment by danilocbueno** [comment]
Para finalizar
- Trocar a cor dos itens do menu para branco
- Retirar os fundos vermelhos e acertar a altura de linha dos textos
- Colocar a pagina sobre como sendo a pagina inicial
- Procurar uma nova fonte semelhante a já utilizada para os titulos

**Comment by maLu70** [comment]
https://www.figma.com/design/opOkkoMQTRav1Idgh6p2j8/Untitled?node-id=0-1&t=hWU6EBjLZ33j8oN2-1
