### ISSUE TITLE
Relatório mês de Agosto

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#119]
Fazer o relatório do mês seguindo o padrão abaixo. 
Colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X + Y horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by maLu70** [comment]
**Agosto**

Semana 31

- 06 Horas: Criação do template para o PHI Lab no Figma
- 01 Horas: Criação de um design para a camiseta da Fábrica de Software 

Semana 32

-  02 Horas: Ajustes finais no template para o PHI Lab

Semana 33

- 02 Horas: Criação de cartazes de divulgação da Fabrica para o Casa Aberta

Semana 35

- 11 Horas: Apresentação da Fabrica de Software no Casa Aberta
- 05 Horas: Organização do espaço para o Casa Aberta


**Total: 27 Horas**

**Comment by Leo2828** [comment]
# Agosto
## Semana 31

- 5 horas: Reunião com a apresentação da escolha de ferramenta para novo projeto.

## Semana 32

- 5 horas: Continuação das pesquisas sobre CMS e desenvolvimento de protótipo de site no figma para o projeto PHILAB.
- 5 horas: Pesquisa de referências para a elaboração do protótipo.
- 5 horas: Reunião semanal apresentando o que foi desenvolvido ao decorrer da semana.
- 5 horas: Prosseguimento com a criação do design do protótipo.

## Semana 33

- 5 horas: Desenvolvimento de um cartaz para apresentação no evento IF casa aberta.
- 5 horas: Verificação dos jogos que seriam apresentados no evento.
- 5 horas: Reunião apresentando o cartaz e informando a situação do jogos.

## Semana 35

- 5 horas: Ajustes no projeto pong.
- 5 horas: Ajustes finais.
- 5 horas: Reunião para a preparação do evento e organização do estande.
- 10 horas: Apresentação da fábrica de software e seus projetos no evento IF casa aberta.

## Total: 65 horas

**Comment by MarcosKauanS** [comment]
# Agosto

## Semana 31
- 02 horas: Menu de opções parte 6: Adicionado todas as opções pedidas ao SpaceInvaders

## Semana 32
- 06 horas: Bug EnemyMap: Testes para tentar resolver o bug do mapeamento dos inimigos
- 02 horas: Menu de opções parte 7: Finalização do menu de opções

## Semana 33
- 04 horas: Consertado bugs dos botões exibidos quando dá game over: Foram consertado os bugs dos botões de game over não ativarem os eventos deles, jogar novamente, ranking 
- 04 horas: Verificação se o usuário está pelo computador ou celular, implementado o bichinho da Luma: Adicionado uma verificação caso o usuário esteja no computador, pedir para ele entrar no celular, implementado o bichinho da Luma

## Semana 34
- 02 horas: Consertado a nave pulando no canvas: Foi resolvido o bug da nave pular na tela
- 02 horas: Testes para finalização: Foram realizados testes para a finalização do SpaceInvaders
- 02 horas: Concatenação da minha parte do projeto com o da Luma: Aconteceu, a concatenação da parte do projeto que a Luma realizou com o meu
- 03 horas: Mudança no volume do som e consertado o ranking: Realizei uma mudança no volume do som para não aparecer uma voz no fundo do áudio, o ranking não estava registrando os players e esse bug foi arrumado

## Semana 35
- 14 horas: IF CASA ABERTA: Fiquei o dia todo, apresentando os projetos da fábrica para os visitantes do IF CASA ABERTA

## Total: 41 horas

**Comment by JoniEmann** [comment]
### Agosto
**Semana 31**

- 05 horas: Reunião com a Fábrica
- 03 horas: tentativa de corrigir o bug de passar os inimigos

**Semana 32**
05 horas: Reunião com a fábrica.

**Semana 33**

- 05 horas: Reunião com a fábrica
- 03 horas: produção do cartaz para o IF-CasaAberta

**Semana 34**

- 05 horas: Reunião com a fábrica
- 03 horas: Conversão dos cartazes para tamanho A3 e mudança de estilo
- 02 horas: Preparando a sala de hardware para a fábrica

**Semana 35**

- 03 horas: auxilio final na parte noturna do IF-CasaAberta para a fábrica.

### Total: 34 horas
