### ISSUE TITLE
Imagem das máquinas da Fábrica

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#29]
As máquinas possuem a mesma imagem com linux instalado. 
É necessário recriar a imagem com a atualização dos softwares utilizados e documentar.

- Definir o SO a ser utilizado;
- Definir a lista de softwares a ser utilizado e documentar;
- Criar a imagem com os softwares;
- Documentar a instalação dos softwares;
- Testar os softwares instalados;
- Testar o fluxo de desenvolvimento;

**Comment by Rafalexandre-code** [comment]
## Sistema operacional : Linux Mint Cinnamon
                                                                                                                                                              * Minha recomendação é o linux Mint Cinnamon, devido a facilidade de interação da interface de usuario além das capacidades de customização e ao fato dele ser o SO convencional para os membros da fábrica.
                              * Caso queira um software mais moderno e voltado para desenvolvedores, recomendo o Fedora que desempenha um peso similar ao do Linux Mint Cinnamon, porém um pouco mais rapido necessitando um pouco mais de experiencia.
                              * Caso queira um sistema extremamente leve para  processamento há o Debian, porém não paresce muito viavel já que a curva de aprendizado do sistema pode acabar levando os membros a demorarem um pouco para entender e adaptar-se ao sistema
                              * Devido a isso a opção mais viável é o Linux Mint Cinnamon
                              
                              ## Lista de softwares
                              * Visual Studio code
                              * * Extensões: Laravel-blade, Live Server, Nuxt, Vue Language Features, Portuguese (Brazil) Language Pack
                              * MySQL Workbench
                              * Atom
                              * Asdf
* Git
* Xampp (ou Laragon)
*

**Comment by Rafalexandre-code** [comment]
## Sistema operacional

* Minha recomendação é o linux Mint Cinnamon, devido a facilidade de interação da interface de usuário, além das capacidades de customização e mais de 30.000 pacotes de recursos gratuitos, aparência semelhante ao Ubunto/Debian sendo utilizado como padrão por muitas empresas do mercado, isso com o fato dele ser o SO convencional para os membros da fábrica.
* Caso queira um software mais moderno e voltado para desenvolvedores, recomendo o Fedora que desempenha um peso similar ao do Linux Mint Cinnamon, porém um pouco mais rápido, porém necessitando um pouco mais de experiência com linux para se mexer nele.
* Uma opção mais moderna de SO é o Manjaro Linux, o Manjaro conta com uma facilidade de uso maior que os outros SO, uma interface mais bonita comparada com os outros e vem com toneladas de software pré-instalado úteis e para diversas situações, além de contar com suporte para arquivos x86-64 e além dos acessos aos repositórios da Arch, no requisito de velocidade ele apresenta o mesmo desempenho que o Linux Mint cinnamon para carregar as coisas, porém ele necessita de mais espaço para a instalação.
* Caso queira um sistema extremamente leve para  processamento há o Debian, porém não parece muito viável já que a curva de aprendizado do sistema pode acabar levando os membros a demorarem um pouco para entender e adaptar-se ao sistema.
* Devido a isso a opção mais viável é o Linux Mint Cinnamon ou o Manjaro caso queira variar os SO da fábrica.
                              
## Lista de softwares
* Visual Studio code
* * Extensões: Laravel-blade, Live Server, Nuxt, Vue Language Features, Portuguese (Brazil) Language Pack
Ferramenta essencial para programar em diversas linguagens, junto a extensões que facilitam a manipulação do Visual Studio code ou extensões necessárias para se rodar certos projetos.
* MySQL Workbench
Ferramenta de banco de dados para armazenar os dados provenientes dos sites.
* Asdf
Gerenciador de versões necessário para rodar as dependencias em suas corretas versões.
* Git
Software para possibilitar fazermos o pull das alterações no GitHub.
* Gimp (ou outro software para design)
Ferramenta para design para que se possa personalizar os sites.
* Php
Linguagem necessária para programarmos sites.
* Composer
Gerenciador de dependências para gerenciarmos todas as dependências necessárias para rodarmos os projetos.
* Docker
* Inkscape

**Comment by danilocbueno** [comment]
- Retirar o xampp/laragon.
- Testar a instalação e configuração do ASDF na distribuição. 
- Adicionar o Docker
- Inkscape
- Navegadores: Google Chrome, Firefox, Edge, Opera.
- PostMan/Insomnia
- Figma
- Fazer Wallpaper!
