### ISSUE TITLE
Fazer relatório do mês de abril

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#47]
Fazer o relatório do mês de abril seguindo o padrão abaixo. 
Pode colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X horas

Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders (issue .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Vitor-G-Cavalheiro** [comment]
# Abril
## Semana 16
- 03 horas: Reunião de planejamento/abertura da fábrica.
- 08 horas: Estudo sobre WebScokets: foi estudado para realizar a comunicação entre o cliente, o jogo e o servidor do projeto SocketInvaders.
## Semana 17
- 04 horas: Refeito o código e as conexões do projeto SocketInvaders para implementação da biblioteca Socket.io.
- 04 horas: Alteração do código base do space invaders e estudo do funcionamento do novo código do jogo para as implementações futuras de APIs.
- 04 horas: Alterando a motivação do space invaders para funcionar com Device Orietation e alterando o evento trigger do tiro, e separação do jogo em duas páginas HTML, uma sendo o controle e outra sendo a tela do jogo.
- 04 horas: Implementando o servidor WebSocket no jogo space invaders, rodando em um html o controle e e em outro html a tela por meio de um servidor js e teste de funcionamento em celulares e nos tablets disponíveis para a fábrica.

# Total 27 horas

**Comment by leonardoDluz** [comment]
# Abril
## Semana 16
- 01 hora: Reunião de planejamento/abertura da fábrica.
- 02 horas: Entendimento do código do projeto IFAQ , implementação do slider com swiperJS e alguns ajustes no html e css do site.
## Semana 17
- 02 hora: Alterações no estilo do site.
- 02 horas: implementação da vizualização de respostas, função de parar ao trocar de slide e animações com animateCss.
- 02 horas: ajustando a responsividade do site.
# Total 9 horas

**Comment by Rafalexandre-code** [comment]
## Abril
## Semana 14
•	02 horas: implementação básica para o pessoal que estava chegando: fizemos uma reunião especificando coisas básicas para os novos integrantes
•	04 horas: distribuição de task: reunião para decidirmos o que iriamos fazer para o casa aberta junto a distribuição do que seria feito para o evento
## Semana 15
•	06 horas: Estudo sobre as Sockets: foi estudado como conseguir fazer a conexão entre cliente e servidor a partir do sockets para o space invaders
•	04 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.
## Semana 16
•	01 horas: arrumar bugs: arrumei alguns bugs que estavam dando no código impedindo que prosseguíssemos
•	04 horas: implementação da função vire seu dispositivo: implementado uma funcionalidade que fala para o usuário vire o dispositivo caso ele não esteja em modo paisagem, junto a algumas concepções no estilo do controle.
## Semana 17
•	02 horas: implementação do sockets para o space invaders: depois de fazer funcionar o sockets implementamos junto ao space invaders e o tornamos funcional chamando-o de socketinvaders.
•	04 horas: reunião da fábrica: reunião para decidirmos o que precisava melhorar ou corrigir do socketinvaders, fora o que ainda era necessário fazer para o casa aberta.

Total: 27 Horas

**Comment by gabs1m** [comment]
# Relatório do mês de abril

## Semana 14

- 04 horas: parte inicial do desenvolvimento do código com api de movimento para space-invaders


## Semana 15

- 08 horas: estudo da tecnologia de websocket


## Semana 16

- 04 horas: continuação do desenvolvimento 


## Semana 17 

- 04 horas: estudo do novo código do space-invaders
- 04 horas: implementação da api de movimento no space-invaders
- 02 horas: troca do eixo da orientação da api de movimento
- 04 horas: implementação do websocket no space-invaders

Total: 30 horas

**Comment by Martins-pedro23** [comment]
# Abril

## Semana 16

- 03 hora: Reunião de planejamento/abertura da fábrica;
- 04 horas: Estudo do código do projeto IFAQ, da tecnologia SwiperJs  e sua implementação.

***

## Semana 17

- 03 horas: Alterações no estilo do site IFAQ;
- 03 horas: Reunião de analise de progresso no projeto IFAQ;
- 04 horas: implementação de animações, e efeitos visuais no site do IFAQ.

***

## Total 17 horas
