### ISSUE TITLE
Analisar projeto GeekIF

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#52]
A ideia é analisar o projeto como um todo e propor melhorias de diferentes frentes. 

Uma frente de análise do código mesmo verificando como está, identificando possíveis problemas e documentando. 
Na segunda frente questões relacionadas ao design da página e suas funcionalidades (o que está legal, o que pode melhorar). Documentar a análise aqui na issue mesmo e apresentar na próxima reunião.

Repositório com o código atual:
https://github.com/CorreaJo/geekif

**Comment by Vitor-G-Cavalheiro** [comment]
## Análise do código
- Página inicial ganhando barra de rolagem horizontal, deixando "organização" para fora da tela
- Diversas partes não necessárias no css, como partes repetidas e partes que não mudam o site
- Classes sem uso
- Indentações incorretas
- Background da parte "PARTICIPE!" se repetindo
- Erros de português ao longo do site
- Páginas "em breve" não estão mostrando as imagens de apoiadores e patrocinadores
- Seria interessante adicionar nos slides os links que os representam
## Análise de design
- A paleta de cores do site não está harmônica
- Refazer os slides
- Mudar os backgrounds
- Remover o contador do final da página
- Padronização das capas das atrações
- Seria interessante disponibilizar para o usuário a opção de ver um slide específico
- Diminuir a opacidade do fundo preto das páginas de conteúdo
- Separação das oficinas em blocos separados
- Padronização das fontes dos subtítulos 
- Adicionar um menu que acompanhe o usuário para ele ter a opção de navegar pelo site sem a necessidade de ficar voltando para o topo da página

**Comment by Martins-pedro23** [comment]
# **Analise design** 

> 1. Muitas cores que não pertencem a uma paleta
> 2. Excesso de imagens 
> 2. Contraste muito grande entre a cor do fundo e as cores usadas 
> 3. Falta de padronização das fontes
> 5. Responsividade ruim 
> 6. Muita informação
> 7. Páginas inteiras de puro texto 
> 8. Imagens do slider não são padronizadas
 
# **Performance**
> 1. Imagens com resolução grande
> 2. Não usar imagens no lugar de SVGs
> 3. Muitas imagens dentro da pasta SRC que não estão sendo utilizadas
> 4. Uma pasta Unused  de imagens não utilizadas
> 5. Script sem necessidade

# **Boas práticas**
> 1. Falta de padronização do nome(nomes em inglês e português)
> 2. Apenas um arquivo CSS para todas as páginas
> 3. O script JS dentro do arquivo HTML
> 4. Código sem endentação
> 5. Código repetitivo
> 6. Tags não sendo utilizadas


# **Recomendações**
> 1. Utilizar Tab2 em vez de Tab4
> 2. Usar o Prettier
> 3. Usar o copilot (todos temos acesso)
> 4. Utilizar bibliotecas ou frameworks externas

**Comment by gabs1m** [comment]
# Problemas

## Design
- Não há uma padronização na formatação das fontes
- Alguns trechos estão sem estilo (fonte padrão do navegador)
- CSS dos ícones do cabeçalho está ruim
- Sobrecarga de informação (muitas cores e elementos)
- Não há uma paleta de cores que combinem
- Slider precisa ser melhorado


## Performance
- Site muito pesado por conta das imagens
- Imagens não responsivas (perdem qualidade ao redimensionar)
- Não possui certificado de segurança (https)


## Organização
- CSS dividido em diferentes arquivos (confuso)
- Código HTML e CSS repetidos em diversos casos (redundante)
- Imagens inutilizadas ocupando espaço no projeto


# Possíveis soluções
- Usar SVGs nos ícones do site
- Criar diversos arquivos CSS para diferentes componentes OU organizar melhor todo o conteúdo em um arquivo
- Usar alguma ferramenta que permita importar código para evitar repetições (PHP)
- Utilizar bibliotecas CSS (Bootstrap, Tailwind) para estilizar componentes

**Comment by leonardoDluz** [comment]
# Análise GeekIF
## Design 
- muita poluição visual (muitas cores, elementos e imagens)
- a paleta de cores não combina
- os campos de texto no site não tem margem lateral nenhuma (quando em telas menores)
- cabeçalho com muitas informações (logo do ifsp e os links de rede social)
- melhorar o slider
  - permitir que o usuário troque de slide
  - fazer um slider que se adapte melhor em telas menores
 ## Boas Práticas
- algumas partes do código não estão indentadas 
- no css algumas tags estão repetidas
- classes que não estão sendo utilizadas
- tags html sendo utilizadas de forma errada (o menu de navegação inteiro dentro de um label)
- imagens que não estão sendo utilizadas
- não há uma pasta para o css, todas estão na raiz do projeto
- excesso de divs quando a utilização de um display flex seria uma opção melhor
## Sugestões
- utilizar a abordagem mobile first para melhorar a responsividade do site
- mais atenção às boas práticas
- utilização de bibliotecas para facilitar o desenvolvimento

**Comment by danilocbueno** [comment]
fazer um resumo das contribuições
