### ISSUE TITLE
Relatório do mês de Maio

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#56]
Fazer o relatório do mês seguindo o padrão abaixo. 
Pode colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X horas

Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders (issue .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Vitor-G-Cavalheiro** [comment]
# Maio
## Semana 18
- 05 horas: Finalização do funcionamento do jogo space inavders em dois dispositivos diferentes e teste do jogo nos tablets
- 05 horas: Concerto da página HTML responsável pelo controle finalizando a conexão do controle com o sever e a conexão do server com o jogo
- 05 horas: Implementação da API ScreenOrietantion para travar a visualização do controle no celular e modificações no código do controle para melhor funcionamento nos tablets, observação e planejamento do espaço de apresentação do IF casa aberta
- 05 horas: Customização dos controles para mostrar a logo do Instituto Feferal e da Fábrica de Software, testando a customização em celulares

## Semana 19
- 05 horas: Correção da falta de efeitos sonoros do space invaders, e estudo para a implementação de um limite de jogadores simultaneamente no jogo 
- 05 horas: Correção do funcionamento do controle no servidor, e preparativos para o If casa aberta, como produção de slides e organização do espaço 
- 07 horas: Realização do evento If Casa Aberta, monitoramento e apresentação dos projetos socket invaders e IFAQ, e apresentação da Fábrica de Software
- 03 horas: Análise meticulosa do site da Fábrica, para levantamento de melhorias, correções e modificações, testes em diferentes telas e aparelhos

## Semana 20
- 05 horas: Estudo sobre tecnologia Greenwood e estudo em cima do código fonte do site da Fábrica para realizar as alterações e correções necessárias 
- 05 horas: Reunião semanal para organização das próximas tarefas, levantamento de pontos positivos e negativos dos últimos trabalhos e como melhora-los, transcrição da reunião em um arquivo RD para documentar as mudanças e novas ideias planejadas
- 05 horas: Análise do código e do design do GeekIF tendo como foco a correção de erros e a busca por melhorias para a implementação no site, tudo sendo documentando na Issue. Realização de um protótipo corrigindo os erros e alterando partes do design do site original
- 05 horas: Confecção de vários protótipos de design para o site do geek If e aprofundamento e melhoramento de ideias para a nova estilização do site e para novos projetos 

## Semana 21
- 05 horas: estudo do jogo pong e de como realizar a Implementação de socket io para transformar o jogo base em um player vs player online e discussão de ideias para projetos apresentáveis no geek if
- 05 horas: importação do código do pong e Implementação do socket io no jogo, sincronizando o movimento do player1 e do player2, implementação de limite de jogadores
- 05 horas: reunião sobre o projeto do geek If, organização e preparação para início do projeto, debate de ideias de design e da criação de uma nova identidade visual, separação em grupos para cada grupo apresentar um protótipo de site visando melhorar o design atual
- 05 horas: estudo da plataforma figma e de ideias e propostas de design para o site do geek If, confecção de três protótipos para debater entre meu colega de grupo qual será nossa abordagem

## Semana 22
- 10 horas: elaboração da versão game do protótipo de landing page do geek if, com versões mobile e desktop, discussão e aplicação de ideias entre o grupo, realização da logo, estruturação do site e apuração das imagens que vão ser utilizadas no projeto final
- 05 horas: apresentação dos protótipos do geek If na reunião, debate de possíveis melhorias e dos próximos passos a serem trabalhados no site do geek If, como as novas páginas, modo de organização e pequenas melhorias nos protótipos já desenvolvidos

# Total: 95 Horas

**Comment by leonardoDluz** [comment]
# Maio

## semana 18
- 02 horas: ajustes no código do projeto ifaq

## semana 19
- 07 horas: Realização do evento If Casa Aberta, monitoramento e apresentação dos projetos socket invaders e IFAQ, e apresentação da Fábrica de Software

## semana 20
- 05 horas: Reunião semanal para revisão dos pontos positivos, negativos, sugestões para melhora e novas ideias
-  03 horas: análise do código do projeto do geek if buscando seus pontos negativos e sugestões para melhorar

## semana 21
- 05 horas: reunião sobre o projeto do geek If, organização e preparação para início do projeto, debate de ideias de design e da criação de uma nova identidade visual, separação em grupos para cada grupo apresentar um protótipo de site visando melhorar o design atual
- 03 horas: início da elaboração do protótipo de landing page do geek if 

## semana 22
- 10 horas: elaboração da versão game do protótipo de landing page do geek if, com versões mobile e desktop, discussão e aplicação de ideias entre o grupo,
- 05 horas: apresentação dos protótipos do geek If na reunião, debate de possíveis melhorias e dos próximos passos a serem trabalhados no site do geek If, como as novas páginas, modo de organização e pequenas melhorias nos protótipos já desenvolvidos

# Total: 40 Horas

**Comment by gabs1m** [comment]
# Relatório do mês de maio

## Semana 18
- 04 horas: implementação do código da API de movimento no novo space-invaders
- 04 horas: implementação de controle juntamente à tecnologia de websocket no novo space-invaders

## Semana 19
- 08 horas: atuação no evento IF Casa Aberta

## Semana 20
- 04 horas: contribuição na retrospectiva da Fábrica de Software
- 04 horas: análise do site do GeekIF 2022

## Semana 21: 
- 04 horas: contribuição para discussão sobre identidade visual do site do GeekIF 2023
- 08 horas: desenvolvimento da versão party do protótipo da landing page do site do GeekIF 2023

## Semana 22: 
- 08 horas: desenvolvimento da versão party do protótipo da landing page do site do GeekIF 2023

### Total: 44 horas

**Comment by Martins-pedro23** [comment]
# Relatório mês de Maio

## semana 18:

- 02 horas: ajustes no designe do IFAQ;
- 05 horas: reunião sobre os ajustes finais para os projetos do IFAQ e Socket Invaders;
- 01 hora: ajustes no código do IFAQ.

***

## semana 19

- 01 hora: Ajustes nos textos do IFAQ;
- 02 horas: Atuação no evento IF Casa Aberta.

***

## semana 20

- 05 horas: Contribuição na reunião de retrospectiva da Fabrica de Software;
- 03 horas: Análise do código do site do evento Geek IF;
- 01 hora: Elaboração texto com pontos negativos levantados na analise anterior.

***
## semana 21
- 05 horas: Reunião para elaboração da nova identidade visual do site do evento Geek IF, definição de metas para o desenvolvimento e a abordagem a ser tomada;
- 08 horas: desenvolvimento do protótipo da landing page do site do GeekIF 2023

***

## semana 22

- 08 horas: desenvolvimento do protótipo da landing page do site do GeekIF 2023

Total: 41 Horas

**Comment by Rafalexandre-code** [comment]
## Semana 18
* 08 horas: implementação no código do space-invaders para limitar a quantidade de usuarios usando IP e JSON
* 04 horas: Finalização do jogo space-invaders e teste do jogo nos tablets
## Semana 19
* 06 horas: atuação no evento IF Casa Aberta
## Semana 20
* 01 hora: elaboração do relatório de Abril
## Semana 21
## Semana 22
* 01 hora: elaboração do relatório de Maio

Total: 20 horas
