### ISSUE TITLE
Relatório Mês de Junho

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#57]
Fazer o relatório do mês seguindo o padrão abaixo. 
Pode colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders (issue .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Vitor-G-Cavalheiro** [comment]
# Junho
- 05 horas: Criação de um [reset.css](http://reset.css/), junção dos dois protótipos apresentados, criação de um protótipo figma para a versão final, criação e implementação das versões mobile e desktop da landing page oficial do geek if

## Semana 23
- 05 horas: Criação e começo das implementações da landing page do geek If, estudando as melhores opções de slider e de menu bar, implementando o menu bar por completo e começo da implementação do slider
- 05 horas: Implementação dos dois sliders no projeto Geek IF e aplicação da responsividade em ambos os sliders, aperfeiçoamento do código e troca do slider antigo por um código novo 
- 05 horas: Finalização das funcionalidades da landing page do Geek IF, troca do código do segundo slider, implementação das áreas sobre, como chegar, contato e rodapé, implementação do Google maps, adaptação do código para melhorar a responsividade

## Semana 24
- 05 horas: Correção de bugs, como o hover dos botões do slider não funcionar, o menu superior não fixo na página, a seção de contato quebrando o HTML, e implementação de sub menus responsivos e aprimoramento do código CSS, HTML e Javascript 
- 05 horas: Integração do Código JavaScript, responsável por enviar emails, na Landing Page, correção de bugs relacionados a responsividade, como textos grandes e imagens tortas, alterações na estilização para melhorar a visualização, Implementação dos links das redes sociais e anotação das práticas utilizadas no código
- 05 horas: Reunião semanal para organização do planejamento e novas metas da semana, apresentação do projeto da landing page, padronização das medidas utilizadas no CSS e estudo para implementação de sub-menus que fechem sozinhos
- 05 horas: Finalização da nova função dos sub-menus, Implementação do logo do projeto, aprimoramento na responsividade das novas alterações, implementação das cores e fontes do styleguide na Landing page do Geek IF 

## Semana 25
- 05 horas: Finalização da implementação do styleguide e estudo para implementação de um slider com a funcionalidade de poder ser arrastado com o click ou touch. Primeiros testes com sliders responsivos com a funcionalidade de grab
- 05 horas: Adição dos realizadores no footer, implementação teste de imagens do evento na Landing Page, estudo de bibliotecas js para implementação de um slider, foram estudadas as bibliotecas [swiper.js](http://swiper.js/), [glide.js](http://glide.js/) e [glider.js](http://glider.js/), confecção de um teste utilizando a biblioteca [glide.js](http://glide.js/)
- 05 horas: Realização de correções e ajustes na Landing page, durante a reunião semanal, como troca do slider principal por um banner estático, ajustes mas logos dos realizadores, adição dos torneios, oficinas, shows e jogos. Participação na reunião e votação do PDI
- 05 horas: Atualização da Landing Page do Geek If, Implementação do banner estático responsivo, correção do slider de eventos que quebrava em certas páginas, adição do conteúdo da página, troca de imagens do slider de eventos e correção das responsividade em tablets

## Semana 26
- 05 horas: Realização de alterações pedidas pelos organizadores do evento, como adição de mais salas de jogos, remoção de algumas oficinas, correção das logos no footer, adição de novos elementos na página, aprimoramento da responsividade em tablets, alterar o redirecionamento dos emails e alterações nos textos da página 
- 05 horas: Estudo e Implementação da biblioteca [fslightbox.js](http://fslightbox.js/) para uso em uma nova página dedicada a galeria do evento, criação da página galeria e estilização da mesma, correção de responsividade na página e adição do link para ela nas demais páginas, organização da galeria
- 05 horas: Reunião semanal para organização de ideias e cronogramas, correção de mais erros relacionados à responsividade, alterações dinâmicas na página de galeria, discussão de ideias e sobre o projeto e a sua documentação, correção de links errados nas páginas internas do site
- 05 horas: Adição de descrição nas páginas internas do site e correção do menu js das mesmas páginas, correção nas páginas internas para funcionamento da responsividade evitando a página de quebrar, aprimoramento nas imagens da galeria e alterações nas páginas internas alterando descrição e organização interna

# Total: 80 horas

**Comment by leonardoDluz** [comment]
# Junho
## Semana 23

- 04 horas: Pesquisa de soluções para envio email pelo site do Geek IF.
- 04 horas: testes de envio de email com a API do formsubmit.co.  

## Semana 24
- 05 horas: estudo de consumo de API com JavaScript.
- 04 horas:  integração da API do formsubmit.co com formulário com js para ser utilizado no site do Geek IF.
- 04 horas: Reunião semanal para organização do planejamento e novas metas da semana, apresentação do projeto da landing page, padronização das medidas utilizadas no CSS e estudo para implementação de sub-menus que fechem sozinhos

## Semana 25
- 04 horas: estudo de Node.Js.
- 04 horas: Realização de correções e ajustes na Landing page, durante a reunião semanal, como troca do slider principal por um banner estático, ajustes mas logos dos realizadores, adição dos torneios, oficinas, shows e jogos. Participação na reunião e votação do PDI

## Semana 26
- 04 horas: estudo do freamework expressjs.
- 04 horas: Reunião semanal para organização de ideias e cronogramas, correção de mais erros relacionados à responsividade, alterações dinâmicas na página de galeria, discussão de ideias e sobre o projeto e a sua documentação, correção de links errados nas páginas internas do site


# Total: 37 horas

**Comment by Rafalexandre-code** [comment]
# Julho
## Semana 23
* 00 horas: ausência de tasks e falta da reunião por questões médicas
## Semana 24
* 00 horas: ausência de tasks e falta da reunião por questões médicas
## Semana 25
* 00 horas: ausência de tasks e falta da reunião por questões médicas
## Semana 26
* 04 horas: instalação de um sistema operacional da fábrica o Manjaro Plasma desktop no pendrive e instalação em um PC da fabrica para testar se suporta.
***
# Total: 04 Horas

**Comment by Martins-pedro23** [comment]
# Junho
## Semana 23
- 03 horas: Pesquisa de modelos de documentação;
- 04 horas: Elaboração do modelo inicial de documentação.

## Semana 24
- 05 horas: Aprofundamento na elaboração da documentação;
- 04 horas: Elaboração de um texto de boas praticas para a fabrica.

## Semana 25
- 02 horas: Finalização do texto de boas praticas;
- 03 horas: Reunião de feedback em relação ao texto.

## Semana 26
- 01 hora: revisão do modelo de documentação;
- 08 horas: aplicação do modelo de documentação no projeto ProsaIF  


# Total: 30 horas

**Comment by gabs1m** [comment]
# Relatório do mês de junho

## Semana 23
- 04 horas: finalização do protótipo do site do GeekIF;
- 04 horas: criação de style guide do protótipo do site do GeekIF;

## Semana 24 
- 08 horas: desenvolvimento do style guide do protótipo do site do GeekIF;

## Semana 25
-

## Semana 26
- 04 horas: adição de páginas internas ao site do GeekIF;
- 04 horas: implementação de lazy loading nas páginas do GeekIF;

### Total: 24 horas
