### ISSUE TITLE
Relatório Mês de Julho

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#58]
Fazer o relatório do mês seguindo o padrão abaixo. 
Pode colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X horas

Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders (issue .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Rafalexandre-code** [comment]
# Julho
## Semana 27
* 04 horas: instalação do novo sistema operacional da fábrica o Manjaro GNOME no pendrive para instalar via inicialização em um PC da fabrica para teste.
## Semana 28
* 04 horas: Instalação em um PC da fabrica para testar se funcionava tudo certinho mais a instalação dos requerimentos de softwares necessários para o pessoal poder utilizar.
## Semana 29
* 04 horas: Instalação dos softwares requisitados pela tesk necessários para o trabalho dentro da fábrica
## Semana 30
* 04 horas: identificação e reparação de alguns problemas relacionados ao vscode como a instalação do composer e do php
***
# Total: 16 Horas

**Comment by Vitor-G-Cavalheiro** [comment]
# Julho
## Semana 27
- 05 horas: Finalização das páginas internas do site, corrigindo imagens não responsivas, páginas sem texto, alterações no menus de todas as páginas, aperfeiçoamento da responsividase em tablets
- 05 horas:  Alteração na página inicial, melhorando a visualização do texto e do mascote sem grandes alterações no banner de fundo, realização da responsividade dessa alteração e correção de bugs relacionados a ela
- 05 horas: Debate sobre a galeria do evento e de qual estilo de apresentação utilizar, mantendo o formato galeria, apresentado o problema das imagens muito grandes dividindo a tarefa para mais membros, e organização das pastas de imagens
- 05 horas: Procura e separação de imagens para as atrações novas e as atrações faltantes, tratamento das imagens para reduzir seu peso e deixar o site mais leve, implementação dos novos sub menus relacionados as novas oficinas em todas as páginas 

## Semana 28
- 05 horas: Criação das páginas das novas oficinas, implementação das imagens selecionadas e adição de uma breve descrição assim como realização da responsividade das páginas e correção dos links da menu bar
- 05 horas: Implementação de um novo slider na página inicial, relacionado a alimentação, adicionando imagens e descrições sobre as ONGs que iram participar do evento, correção do slider de eventos com a adição das novas oficinas
- 05 horas: Apresentação e debate sobre as novas mudanças no GEEK IF e no nosso cronograma, com a chegada do evento próxima algumas outras tarefas necessitam de maior atenção de mais membros, como as alterações do GEEK IF e os jogos que serão apresentados no evento 
- 05 horas: Implementação da área patrocinadores e apoiadores no footer de todas as páginas, assim como ajuste em sua responsividade, tratamento de todas as imagens do footer, criação e organização das imagens em pastas pedidas pelo organizador

## Semana 29
- 05 horas: Correções de responsividade das novas páginas e novos elementos integrados na página inicial, correção do banner de alimentação e modificação nas descrições das ONGs, mudanças nas imagens das páginas internas, e redução do tamanho das imagens da galeria
- 05 horas: Reunião semanal para discussão sobre as novas alterações do site GEEK IF, separação de das funções relacionadas ao projeto e debate de mudanças e ferramentas que podem ser aplicadas no site, realização dos relatórios faltantes como o de julho, junho e o parcial, início das alterações no site do GEEK IF
- 05 horas: Aperfeiçoamento da seção patrocinadores e apoiadores nos footers de todas as páginas, alterações no slider das ONGs, correção de responsividade do footer e correção de erros de digitação das novas páginas internas 
- 05 horas: Refatoração do código e aperfeiçoamento da organização do código, adição das novas imagens para as atrações e confecção das novas descrições, implementação dos links externos nas logos do footer

## Semana 30
- 05 horas: Modificação do slider de alimentação, troca por um novo modelo de slider, implementação e aperfeiçoamento da responsividade desse novo slider e adaptações dessa nova versão ao site e seu estilo
- 05 horas: Reunião semanal, apresentação de novas ideias e melhorias para o site do Geek IF, conversa sobre a mudança do slider das ONGs e correção de erro de quebra da página do cosplay infantil, conversando melhorias de performance para o site e como realizá-las 
- 05 horas: Implementação de flechas nos menus, alteração da sessão dedicada as ONGs sendo trocado o slider por uma área com as fotos e links para as ONGs, correção de erros e responsividade e adição do texto dos patrocinadores
- 05 horas: Alterações na página de patrocinadores, corrigindo cor e erros apresentados, implementação dos links, debates sobre os jogos que serão apresentados no GEEK IF, envio do site do GEEK IF para aprovação e/ou alterações e melhorias

## Semana 31
- 05 horas: correção de responsividade do projeto GEEK IF, com erros pequenos em textos, correção principalmente na página seja um patrocinador, adição dos textos sobre as atrações do evento, implementação de mais alguns links dos apoiadores

# Total: 85 Horas

**Comment by Martins-pedro23** [comment]
# Julho
## Semana 27
- 04 horas: Finalização da documentação do ProsaIF;
- 03 horas: Reunião de feedback sobre o modelo de documentação.

## Semana 28
- 08 horas: Estudo da linguagem TypeScript
- 16 horas: Estudo da tecnologia React;
- 08 horas: criação do protótipo para o LabIF Maker 

## Semana 29
- 12 horas: Estudo da tecnologia Next.
- 06 horas: aprofundamento na tecnologia Tailwind
- 04 horas: ajustes do site do LabIF Maker
- 10 horas: desenvolvimento do site do LabIF Maker;

## Semana 30
- 20 horas: desenvolvimento do site do LabIF Maker;
- 05 horas: estudo da plataforma Eletrosfy

## Semana 31
- 0 horas 

# Total: 96 Horas

**Comment by gabs1m** [comment]
# Relatório do mês de julho

## Semana 27
- 08 horas: correção das imagens das páginas do site do GeekIF;

## Semana 28 
- 08 horas: ajuste final das imagens do site do GeekIF;

## Semana 29

## Semana 30

## Semana 31

### Total: 16 horas
