### ISSUE TITLE
Relatório mês de agosto

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#61]
Fazer o relatório do mês seguindo o padrão abaixo. 
Pode colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders (issue .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Vitor-G-Cavalheiro** [comment]
# Agosto
- 05 horas: Estudo sobre o jogo pong e análise do código e de como dar continuidade ao projeto, correção dos controles e finalização na integração do multiplayer, sincronizando a bola para ambos os jogadores, e estudando meios para remover o delay
- 05 horas: Reunião semanal para discussão da continuidade dos projetos e apresentação dos resultados até o momento, alteração no projeto ping pong multiplayer, separação do código do projeto em uma tela e controles, correção do delay dos controles 
- 05 horas: Inversão do jogo Pong, trocando todos os eixos, controles e visualização do jogo para ser jogado na vertical, alteração na colisão da bola, movimentação, velocidade, melhora na resposta dos controles e Implementação da trava de modo de visualização do controle 

## Semana 32
- 05 horas: Implementação de um sistema de pontuação para ambos os players, incrementado da pontuação visual e adição de um limite de pontos para limitação de tempo de jogo e realização de um ponto de reset para não deixar o jogo infinito, estudo de futuras implementações no jogo e modificações para adaptar o jogo para a temática da fábrica de software 
- 05 horas: Refatoração do código do jogo Pong, estilização dos controles e levantamento de ideias para novas adições no jogo e meio de estilizar, testes de desempenho e de responsividade do jogo, organização dos arquivos e pastas do jogo
- 05 horas: Reunião semanal da fábrica para apresentação e testes do jogo Pong, apontamento de erros e ideias para sem implementadas, estilização dos Paddles dos players e do Score de cada um, separação da melhoras adições para o jogo 
- 05 horas: Modificação do projeto GEEK IF, implementação de novas ONGs na área de alimentação, remoção do logo da Romtec do footer, adição dos novos apoiadores, modificação na área de apoiadores para melhorar a legibilidade, Remoção de páginas de oficinas que não estarão presentes no evento

## Semana 33
- 05 horas: Adição de novas páginas de oficinas e de jogos, implementação de descrição e fotos nas novas páginas, alterações e correções pedidas realizadas, ajuste da responsividade das novas páginas 
- 05 horas: Alteração no logo do site e correção de sua responsividade, implementação de uma galeria nova com outra tecnologia, estudo de diversas galerias que poderiam ser aplicadas, finalização da página da galeria e da separação das fotos
- 05 horas: Reunião semanal da fábrica de software, realização de pequenas correções no projeto GEEK IF, como troca das imagens do Kung Fu e do Hapkido, remoção dos links dos apoiadores e remoção de alguns apoiadores, discussão sobre os projetos de jogos do space invaders e do pong
- 05 horas: Atualização do projeto Pong, estilização e adição diferenças entre os players para melhorar o entendimento do jogo, adição de sons ao jogo, implementação do logo da fábrica na tela do jogo

## Semana 34
- 05 horas: Alterações no jogo Pong para melhorar a experiência de usuários com dificuldade no jogo e balancear as partidas, correção do menu do projeto GEEK IF, problemas de responsividade quebrando a página
- 05 horas: Adição de novas Oficinas no projeto GEEK IF, alteração e implementação na sala de jogos, adição de novas descrições e de uma área nova com o mapa do evento, implementação de uma página sobre o cronograma do evento
- 05 horas: Reunião semanal da Fábrica para discussões do andamento dos projetos, realização do upload da versão mais nova do GEEK IF, adição da página do campeonato de cospobre e adição das descrições dos campeonatos 
- 05 horas: Alterações do projeto GEEK IF, correção do menu pequeno da versão mobile e correção dos links inexistentes do menu, troca do mapa do evento, atualização na página sobre Yu-Gi-Oh e adição de imagens, alteração no cronograma 

## Semana 35
- 05 horas: Correção de erros de responsividade no GEEK IF, aprimoramento do código do Pong e testes de funcionalidades, aperfeiçoamento da funcionalidade do Boost, correção de erros em relação ao Boost e de casos onde a barrinha sumia
- 05 horas: Estudo de nova funcionalidade para o site do GEEK IF, implementação de um zoom na imagem do mapa do evento, teste de performance do pong e coleta de ideias para aprimoramentos finais do jogo, estudo para implementação de uma aviso de vencedor no jogo Pong 
- 05 horas: Reunião semanal da fábrica para levantamento de ideias para o Pong e escala para o dia do GEEK IF, implementação da função de reset e de start no jogo Pong, realização de um controle da entrada e saída de players do jogo

# Total: 90 horas

**Comment by Rafalexandre-code** [comment]
# Agosto

## Semana 31
* 5 horas: Reunião semanal para discussão dos projetos
 ---

## Semana 32
* 1 horas: Reunião semanal
* 4 horas: Analise dos erros para rodar a o gerenciador de pacotes asdf
---

## Semana 33
* 1 horas: Reunião semanal
* 5 horas: Correção de algumas bibliotecas para a criação da nova imagem dos PCs da fábrica
---

## Semana 34
* 1 horas: Reunião semanal
* 3 horas: Identificação de um problema de versões do OpenSSL
---

## Semana 35
* 1 horas: Reunião semanal
* 5 horas: Resolução do problema da bibilioteca mais test da imagem em um dos PCs
---
# Total: 26 horas
