### ISSUE TITLE
Levantamento de Problemas e Tarefas Pendentes nos Projetos IFAQ, SpaceInvaders e Pong

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#64]
Esta issue tem como objetivo realizar um levantamento abrangente dos problemas identificados e das tarefas que ainda precisam ser implementadas nos projetos desenvolvidos: IFAQ, SpaceInvaders e Pong. A documentação desses problemas e pendências ajudará a equipe a priorizar o trabalho e a melhorar a eficiência do desenvolvimento.

Tarefas:

1. Análise de Problemas:

- [x] Identificar e listar todos os problemas relatados nos projetos, como erros, bugs, ou comportamentos inesperados.
- [x] Categorizar os problemas por prioridade (alta, média, baixa) e gravidade (crítico, moderado, leve).

2. Tarefas Pendentes:

- [x] Listar todas as tarefas e recursos que ainda precisam ser implementados nos projetos.
- [x] Priorizar as tarefas de acordo com a importância e impacto no projeto.

3. Priorização:
 - [ ] Apresentar aos demais membros para revisar a lista de problemas e tarefas e definir a ordem de priorização.

## Critérios de Aceitação:

- [ ] Todos os problemas e tarefas estão devidamente documentados na issue.
- [ ] Os problemas foram categorizados por prioridade e gravidade.
- [ ] As tarefas pendentes foram priorizadas de acordo com a importância.
- [ ] Responsáveis foram atribuídos a cada problema ou tarefa.
- [ ] A equipe concordou com a priorização estabelecida.

Esta issue servirá como um registro centralizado de problemas e tarefas pendentes em nossos projetos, permitindo que a equipe os aborde de maneira eficaz e colaborativa. Vamos trabalhar juntos para melhorar nossos projetos e entregas.

**Comment by Vitor-G-Cavalheiro** [comment]
## PONG
ERROS E BUGS
    • Quando o player vermelho acerta a bola tem chance dela aparece no meio do campo *Alta Moderado
    • Orientação do celular errada (tá apenas configurado pros tablets) *Alta Grave
    • Bugs de tamanho da barra azul *Baixa Leve
    • Problemas com a trava de orientação *Média Leve

MELHORIAS E IDEIAS
    • Placar similar ao ping pong (jogo real) *Baixa Leve
    • Cabeçalhos informativos (falando sobre o jogo, a fábrica) *Média Moderada
    • Nome do jogo na página *Baixa Leve
    • Mostrar o vencedor (Ex: “player 1 venceu”) *Média Moderada
    • Aparência do controle *Baixa Leve
    • Estilização da página do jogo *Alta Leve
    • Responsivo? *Média Grave
    • Melhor reconhecimento dos usuários (tutorial controles) *Alta Moderada
    • Delay maior no reset *Média Leve

## SPACE INVADERS
ERROS E BUGS
    • Concertar orientação de tela (tablet/celular) *Alta Grave
    • Página placar sem estilização completa *Baixa Leve
    • Nave presa no canto da tela *Média Moderada
    • Tela do jogo vertical com o celular na horizontal *Média Leve
    • Página de ranking bugando (bad gateway) *Alta Grave
    • Reset de tiro por acerto *Baixa Leve

MELHORIAS E IDEIAS
    • Nome do jogo na página (centralizar) *Baixa Leve
    • Finalizar jogo sem encostar nos inimigos *Alta Grave
    • Tutorial do jogo? *Alta Moderada
    • Maior caracterização do jogo com elementos da fábrica *Média Leve

## IFAQ
ERROS E BUGS

MELHORIAS E IDEIAS
