### ISSUE TITLE
Relatório mês de setembro

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#68]
Fazer o relatório do mês seguindo o padrão abaixo. 
Pode colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders (issue .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Vitor-G-Cavalheiro** [comment]
# Setembro
- 05 horas: teste da responsividade e jogabilidade do Pong nos tablets, notação de que os tablets novos não funcionam com inspect device, criação de um blog relatando as tecnologias usadas e o processo de criação do jogo Pong
- 02 horas: Apresentação dos projetos na realização do evento GEEK IF, demonstração e explicações sobre o funcionamento do jogo e como ele foi desenvolvido 

## Semana 36
- 05 horas: Estudo da programação orientada à objeto na linguagem de Java, com base no jogo Pong. Aprofundamento da linguagem Java e do entendimento da Programação Orientada. Escrita do relatório final do mês de Agosto.
- 05 horas: Prática de programação orientada ao objeto utilizando a linguagem Java, estudo de como melhorar o projeto Pong com base nos novos conhecimentos, e melhorias para o jogo base com base no feedback do público

## Semana 37
- 05 horas: Tentativas de implementação de melhorias no pong e busca por erros e bugs, estudo de novas funcionalidades para implementação, continuo estudo sobre programação orientada a objeto
- 05 horas: Busca de erros e bugs no jogo Pong, teste de melhorias, estudo de outros projetos da fábrica para futura análise e criação de um blog para esses devidos projetos, melhora no texto do blog do Pong 
- 05 horas: Reunião semanal, discussão sobre os próximos projetos e a organização das tarefas a serem feitas, e o remanejamento da equipe com a saída de um dos membros, e debate sobre a apresentação da semana científico cultural
- 05 horas: Análise dos projetos Pong, Space invaders e IFAQ para levantamento de erros e bugs, propostas de novas melhorias e ideias para se implementação, e estudo dos projetos para escrever a apresentação

## Semana 38
- 05 horas: Alterações no site da Fábrica, Atualização do processo seletivo, retira do item blogs e incorporação de seu conteúdo na página projetos, correção dos membros da equipe e da página de membros, atualização dos projetos 
- 05 horas: Estilização da página da equipe do site da Fábrica, correção das páginas de membros e atualizações dos membros, implementação de links das redes sociais, organização dos membros e correção de bugs
- 05 horas: Reunião semanal para distribuição de tarefas, treinamento de Laravel para os membros da fábrica, atualização dos links das páginas de membros do site da Fábrica, feitio da publicação da análise de problemas
- 05 horas: Finalização da implementação das redes sociais em todos os perfis de membros, análise e estudo para repaginação da página de todos os membros, levantamento de prioridade dos problemas e tarefas pendentes em outros projetos

## Semana 39
- 05 horas: Organização do levantamento prévio de erros, bugs e melhorias dos outros projetos por ordem de relevância e gravidade do problema, atualização da página de membros da equipe
- 05 horas: Reunião semanal para alinhamento de ideias e debate sobre andamento das alterações e melhorias do site da fábrica, treinamento de git e github
- 05 horas: Participação do evento PHP summit, em palestras sobre modulações, machine learning, a importância dos testes e sua automatização, RFCS do PHP, Banco de dados, entre outras
- 05 horas: Correção e mudanças na responsividade e visual do site da fábrica, atualização visual na página de equipe e aprimoramento da sua versão mobile

# Total: 77 horas

**Comment by danilocbueno** [comment]
@Vitor-G-Cavalheiro , só lembre-se que a linguagem é Javascript e não Java (são duas linguagens diferentes)
