### ISSUE TITLE
Desenvolvimento da Identidade Visual para a Fábrica de Software

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#71]
O objetivo da tarefa é criar uma identidade visual única e representativa para a Fábrica de Software. A identidade visual incluirá a criação de um logotipo, a definição da paleta de cores e a escolha da tipografia que será utilizada no site e em outros materiais de comunicação.

**Tarefas:**
1. **Design do Logotipo:**
Usar como base/modelo os logos anexados ao final da issue. O logo atual apesar de ser bacana não tem proporção entre os elementos e isso é ruim principalmente quando vamos aplicar fora do contexto de site. Além disso, só o logo não identifica do que se trata por isso a importância de se ter escrito o nome do projeto.
   - [x] É importante o logotipo conter o nome do projeto "Fábrica de Software IFSP Itapetininga"
   - [x] É importante que o logo possa ser aplicado em diversos contextos, por exemplo: o site, camiseta, banner, etc.
   - [x] Desenvolver conceitos de logotipos que representem a Fábrica de Software.
   - [x] Criar pelo menos duas opções de logotipos para revisão.

2. **Paleta de Cores:**
   - [x] Definir uma paleta de cores que represente a identidade da Fábrica de Software. Incluindo cores primárias e secundárias.
   - [x] Criar amostras visuais das cores escolhidas (no site)
   - [x] Caso queira manter o laranja, o tom precisa ser modificado mais na linha do exemplo do GeekIF

3. **Tipografia:**
   - [x] Selecionar uma tipografia adequada que seja legível e que se alinhe com a identidade da Fábrica de Software.
   - [x] Definir estilos de texto para títulos, parágrafos e outros elementos.

4. **Aplicação Visual:**
   - [x] Criar exemplo de como a identidade visual será aplicada no site
  
5. **Revisão e Feedback:**
   - [x] Apresentar as opções de logotipos, paleta de cores e tipografia à equipe para revisão e coleta de feedback.
   - [x] Realizar ajustes com base no feedback recebido.

6. **Finalização e Entrega:**
   - [ ] Finalizar o design do logotipo e fornecer os arquivos finais nos formatos apropriados.
   - [ ] Documentar a paleta de cores e a tipografia para referência futura no próprio site da Fábrica.

**Critérios de Aceitação:**
- [ ] Um logotipo representativo e aprovado foi criado.
- [ ] A paleta de cores foi definida e documentada.
- [ ] A tipografia foi escolhida e documentada.
- [ ] A equipe revisou e aprovou a identidade visual proposta.
- [ ] Todos os materiais finais foram entregues nos formatos necessários.

Modelos:
![Image](https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/assets/2002182/f20d6dfc-53de-4cd2-a0be-765cc6942219)
![Image](https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/assets/2002182/702b50b2-e284-4a1f-8535-11e7b763db58)

**Comment by Vitor-G-Cavalheiro** [comment]
![99 Sem Título_20231113135825](https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/assets/126813410/6e5d0558-5c61-4c12-8057-2c9f20b28b05)
![99 Sem Título_20231113135922](https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/assets/126813410/6789cf5d-b549-4e81-b231-a372401119ba)
![99 Sem Título_20231113140133](https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/assets/126813410/6157317e-6ca7-486c-a590-0d3068bb357c)
