### ISSUE TITLE
Relatório mês de novembro

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#76]
Fazer o relatório do mês seguindo o padrão abaixo. 
Pode colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders (issue .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Vitor-G-Cavalheiro** [comment]
# Novembro
- 04 horas:  Participação da semana científica cultural na exibição dos projetos, vistoria dos projetos relacionados a informática e suas técnicas de desenvolvimento 

## Semana 45
- 05 horas: Alterações nos protótipos de logo, aplicação em modelos reais e testes com a paleta de cores atual, assim como análise de possíveis mudanças de estilo para o site
- 05 horas: Experimentação da logo em produção em camisetas, modificações na logo e testes de seu uso em slides e apresentações, exportação da logo em modelo próprio para uso
- 05 horas: Reunião semanal para apresentação do protótipo de logo e coleta de feedbacks, continuação do treinamento Laravel entrando em conceitos de MVC com o foco em controladores e visões
- 05 horas: Refacção do protótipo de logo, com as mudanças recebidas no feedback, assim como implementação da nova versão da logo em exemplos visuais como site e app

## Semana 46
- 05 horas: Realização do novo logotipo nas suas duas versões, exportação do logo em PNG para ser utilizado em diversos ambientes, assim como remoção do background e aprimoramento da qualidade da imagem
- 05 horas: Testes de paletas de cores para o novo logo, assim como estudado da tipografia e de possíveis mudanças para melhor interação com o logo, assim como adaptação do mesmo para se manter harmônico ao site da fábrica 
- 05 horas: Estudo sobre PHP AJAX para melhor compreensão da tecnologia e utilização da mesma em novos projetos e possível implementação em projetos atuais, visando adquirir novos conhecimentos e conhecer novas tecnologias para uso
- 05 horas:  Implementações testes de PHP AJAX utilizando a tecnologia em um ambiente simulado de necessidade para melhor compreensão da tecnologia e estudo na prática do funcionamento da tecnologia

## Semana 47
- 05 horas: Estudo sobre o framework Laravel em paralelo ao treinamento, realizando testes com o projeto do treinamento e projetos novos, também entendo melhor como funciona o framework e a estrutura MVC
- 05 horas: Reunião semanal e continuação do treinamento Laravel, agora vendo módulos e como o framework interage e trabalha em conjunto com o SQL, criando um método de Inserir informações no banco
- 05 horas: Estudo do Laravel e realização da criação de um método de editar um dos valores da tabela, utilizando dos conceitos apreendidos ao longo do treinamento e buscando novas informações com base na documentação laravel
- 05 horas: Continuação do estudo Laravel, agora abordando as funções de detalhes/selecta e delete, utilizando da documentação para conhecer a sintaxe e criar ambas as operações

## Semana 48
- 05 horas: Continuação do estudo Laravel, explorando novas funções e simplificações do framework, conhecendo sua sintaxe e sua estruturação, assim como estudando outros comandos do Laravel e sua ligação com o banco
- 05 horas: Vendo diferentes métodos de aplicação Laravel, estudando os projetos da fábrica que utilizam o framework, para entender como o projeto se relaciona com o framework e utiliza das ferramentas disponibilizadas pelo mesmo
- 05 horas: Reunião semanal e amostra das funções CRUD realizadas em Laravel nesse meio tempo de estudo, compreensão de diferentes formas de realizar o CRUD e agilizar o desenvolvimento
- 05 horas: Criação do roteiro para o vídeo de depoimento, assim como confecção do relatório de novembro e do relatório final, e gravação do vídeo de depoimento sobre a experiência na fábrica
# Total: 84 horas
