### ISSUE TITLE
Atualizações do site da Fábrica

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#81]
- [x] Estudar sobre astro (https://astro.build/)
- [x] Verificar a viabilidade de aplicar no Site da Fábrica
- [x] Criar uma branch nova no repositório e tentar adaptar o site da fábrica ao astro
- [x] A partir da logo desenvolvida em (https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/issues/71) criar um formato SVG final e incorporar no site da Fábrica
- [x] Fazer uma proposta de layout/template da fábrica 3.0 (https://astro.build/themes/)
- [x] Como incorporar o tailwind no astro?
- [x] Definir uma paleta de cores (com um novo laranja ou mesmo outra cor)
- [x] Adaptar o novo template ao site da fábrica

## Correções
- [x] Modal no dispositivo móvel
- [x] Controle do video no modal
- [x] Loop está com erro para voltar no slider
- [x] Arrumar o slider do projetos
- [x] Corrigir responsividade do Modal

**Comment by Leo2828** [comment]
## Proposta layout fábrica:

- Textos maiores e chamativos
- Maior presença da paleta de cores da fábrica
- Botões de ações com incentivo de conhecer os projetos
- Destaque de projetos
- Mais conteúdo na página inicial - depoimentos escritos, 
- Seção da equipe com mais informações
- Depoimento em video aparece quando entra em mais detalhes da pessoa específica
- Seção Sobre mais elaborada 

- Z-Pattern 
	*Ex.(https://trial-landing-tailwind.netlify.app/)

- Relatos escritos de antigos membros aparecendo através de um slider 	
	͘*Ex.(https://astroship-pro.web3templates.com/#)
	*Como fazer (https://codepen.io/hbadri-dev/pen/KKBqxvQ)

- Foto do projeto que ao clicar mostra um menu com mais detalhes	
	*Ex.(https://sven-astro.netlify.app/)
	*Como fazer (https://www.w3schools.com/jsref/event_onclick.asp)

- Pagina de Membros como uma ficha que aparece após o click do mouse
	*Ex.(https://www.rokt.com/about-us/)
	*Como fazer (https://www.w3schools.com/jsref/event_onclick.asp)

- Topicos aparecendo suavemente 
	*Ex.(https://agency-aestro-astro.netlify.app/)
	*Como fazer (https://codepen.io/esemega/pen/LYGNRoB)

- Hero desce junto com o scroll
	ex. Como fazer (https://codepen.io/michaelfangman/pen/kWqbeb)

ideias maluca:
	- (https://codepen.io/isladjan/pen/abdyPBw)

**Comment by danilocbueno** [comment]
[  ] Trocar description 
[  ] Testar o compartilhamento das redes sociais (facebook, twiter, instagram)
[  ] Verificar como publicar o site
