### ISSUE TITLE
Relatório do mês de Maio

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/fabsoftware.itp.ifsp.edu.br#87]
Fazer o relatório do mês seguindo o padrão abaixo. 
Colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X + Y horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Leo2828** [comment]
# Maio
## Semana 17

- 05 horas: Reunião com resultados sobre resultados sobre a viabilidade da substituição da framework Greenwood para Astro Js no site da fábrica

## Semana 18

- 05 horas: Início da implementação da framework Astro Js no site
- 05 horas: Substituição das ferramentas do Greewood 
- 05 horas: Componentização e ajustes gerais no site 
- 05 horas: Reunião com a finalização da implementação e assignação da tarefa de criar um novo layout para o site da fábrica

## Semana 19

- 05 horas: Pesquisas por templates prontos no site: [](https://astro.build/themes/), que possuem um perfil que encaixe ao site da fábrica
- 05 horas: Estudo geral sobre layouts de websites
- 05 horas: Síntese e anotação das ideias formuladas com exemplos, funcionalidades e como realizar implementação:[ #81](https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/issues/81#issuecomment-2115800618) 
- 05 horas: Apresentação das ideias e verificação da possibilidade de efetivação

## Semana 20

- 05 horas: Começo da implementação das ideias apresentadas e substituição da framework Bootstrap por Tailwind
- 05 horas: Familiarização com Tailwind e estilização do site com enfoque na página inicial
- 05 horas: Continuação da estilização e aplicação das idéias propostas
- 05 horas: Exposição do resultado parcial da página inicial e coleta de feedbacks

## Semana 21

- 05 horas: Seguimento da estilização do site da fábrica com mudanças na paleta de cores e mudanças nos arquivos dos projetos
- 05 horas: Substituição da seção de depoimentos com os vídeos por slider de cards que passam suavemente com trechos dos vídeos escritos
- 05 horas: Finalização da seção de depoimentos com inclusão de modais com vídeos que aparecem após o click de algum card do slider e acrescentação de animação ao scroll do mouse na página inicial

## Total: 80 horas

**Comment by MarcosFabSoftware** [comment]
# Maio
## Semana 18
- 04 horas: Versão inicial dos videos: Foi feita  a finalização da versão inicial dos videos
## Semana 19
- 01 horas: Versão inicial do WebStories: Ocorreu a construção de uma versão inicial do WebStories utilizando os videos
- 01 horas: Edição dos áudios: Uma edição nos áudios foi realizada
- 02 horas: Modificação na responsividade: Foi realizada uma modificação na responsividade
- 04 horas: Testes e mudanças no JavaScript: Foi realizado testes e mudanças no JavaScript, de modo a adaptar as animações do video teste do IFAQ, como a animação de digitação ou a de aparecer (fade-in)
## Semana 20
- 02 horas: Mudanças no CSS: Foram realizadas várias mudanças no CSS para um melhor layout e uma melhor responsividade
- 02 horas: Testes para uma melhor responsividade: Para uma melhor responsividade, foi utilizado uma ferramenta para tirar o fundo das imagens, além de ser realizado vários testes com esta ferramenta
- 02 horas: Testes com um slider: Foram realizados testes com um slider, feito inteiramente com JavaScript, mas não foi realizado a implementação do mesmo
## Semana 21
- 02 horas: Mudança na barrinha verde: Foi feito uma mudança na barrinha verde, de modo que ela funcione somente com css, além dela agora ficar totalmente na vertical e no meio do Stories
- 02 horas: Modificação para uma melhor responsividade: Para ter uma melhor responsividade, foram feitas modificações no arquivo CSS
- 02 horas: Implementação do slider: Ocorreu a implementação do slider, por meio de CSS e JavaScript, além da adição das imagens
- 02 horas: Modificação na responsividade, adicionado áudio: Foram realizadas modificações na responsividade e adicionado um áudio teste no WebStories
- 03 horas: Modificações em todo WebStories: Ocorreu uma mudança na fonte que é utilizada no WebStories, modificação na responsividade e mudança para o WebStories usar somente animações do próprio AMP Stories
## Semana 22
- 02 horas: Modificação no slider: Troca do slider, para um "slider" feito somento com animações do AMP Stories, tentativa de melhora na responsividade


Total: 31 horas

**Comment by maLu70** [comment]
### Semana 18

- 01 Hora: Pesquisa sobre como adicionar efeito de zoom no carrossel de imagens.

- 04 Horas: Ajustes no vídeo do WebStories: adicionado zoom nas imagens, sincronização do áudio com o texto e troca do hexágonos por quadrados.

### Semana 19:

- 05 Horas: Pesquisa e aplicação de ideias para a página inicial do IFAQ. 

### Semana 20:

- 01 Hora: Ajustes finais na página inicial do IFAQ: espaçamento entre os elementos e transparência do botão.

- 01 Hora: Escolha de uma nova fonte.

### Semana 21

- 04 Horas: Seleção de 6 imagens para cada pergunta do IFAQ.

### Total: 16 Horas

**Comment by JoniEmann** [comment]
**MAIO**
... 
**Semana 18**
- 02 horas: Observação e análise dos vídeos, cujo foram realizadas testes de responsividade.
... 
**Semana 19**
- 02 horas: Após a indexação dos vídeos no WebStories com os áudios, procura de elementos naturais do próprio AMP stories para usar.
- 05 horas: Reunião de demonstração dos trabalhos realizados após a escolha do vídeo, como sua inserção no amp stories por vídeo. 
... 
**Semana 20**
- 01 horas: Testando a separação do vídeo/imagem, usando CSS para dar um formato a imagem pra ficar rente a linha verde na diagonal, vendo que vídeo não era viável. 
- 04 horas: Usando o código frame que Marcos Kauan fez, realizado testes de responsividade de dispositivo em dispositivo, seja separando elementos ou agrupando, para que o slider fique rente à linha na diagonal.
- 02 horas: Testes com um slider: Foram realizados testes com um slider, feito inteiramente com JavaScript, mas não foi realizado a implementação do mesmo. 
... 
**Semana 21**
- 02 horas: mudanças de planos, a barra verde que antes na diagonal iria se tornar um elemento individual, feito a parte de imagem, retirando o fundo e mantendo a ideia original. 
- 01 hora: Testes de formatação, melhorando posição do texto e tentando deixá-lo mais ma horizontal do que na vertical.
... 
**Total: 19 horas**
